apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: c1
          image: kishor1993/v2
          ports:
            - containerPort: 80


